apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: default 

