apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprormq01
  labels:
    app: vprormq01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprormq01
  template:
    metadata:
      labels:
        app: vprormq01
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq
          ports:
            - containerPort: 5672  
          env:
            - name: rabiitmq_pass
              valueFrom:
                secretKeyRef:
                   name: app-Secret
                   key: rmq-pass 
